### ISSUE TITLE
Build error on Heroku

### ISSUE THREAD

**Issue by moul** [hull-ships/hull-webhooks#6] opened 2017-02-17 17:52 UTC
The **Deploy on Heroku** button seems to be temporarily broken, I don't understand why the `babel` binary cannot be found, the `babel-cli` package is mentioned in the `package.json`, may the error comes from Heroku?

```
-----> Deleting 1 files matching .slugignore patterns.
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  5.x
       engines.npm (package.json):   2.x
       
       Resolving node version 5.x via semver.io...
       Downloading and installing node 5.12.0...
       Resolving npm version 2.x via semver.io...
       Downloading and installing npm 2.15.11 (replacing version 3.8.6)...
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Installing node modules (package.json)
       
       > hull-ship-base@0.1.0 postinstall /tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/node_modules/hull-ship-base
       > npm run build
       
       
       > hull-ship-base@0.1.0 build /tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/node_modules/hull-ship-base
       > npm run clean && npm run build:server
       
       
       > hull-ship-base@0.1.0 clean /tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/node_modules/hull-ship-base
       > rimraf lib
       
       
       > hull-ship-base@0.1.0 build:server /tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/node_modules/hull-ship-base
       > babel src -d lib
       
       sh: 1: babel: not found
       
       npm ERR! Linux 3.13.0-105-generic
       npm ERR! argv "/tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/.heroku/node/bin/node" "/tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/.heroku/node/bin/npm" "run" "build:server"
       npm ERR! node v5.12.0
       npm ERR! npm  v2.15.11
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! hull-ship-base@0.1.0 build:server: `babel src -d lib`
       npm ERR! spawn ENOENT
       npm ERR!
       npm ERR! Failed at the hull-ship-base@0.1.0 build:server script 'babel src -d lib'.
       npm ERR! This is most likely a problem with the hull-ship-base package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     babel src -d lib
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs hull-ship-base
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!
       npm ERR!     npm owner ls hull-ship-base
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/node_modules/hull-ship-base/npm-debug.log
       
       npm ERR! Linux 3.13.0-105-generic
       npm ERR! argv "/tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/.heroku/node/bin/node" "/tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/.heroku/node/bin/npm" "run" "build"
       npm ERR! node v5.12.0
       npm ERR! npm  v2.15.11
       npm ERR! code ELIFECYCLE
       npm ERR! hull-ship-base@0.1.0 build: `npm run clean && npm run build:server`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the hull-ship-base@0.1.0 build script 'npm run clean && npm run build:server'.
       npm ERR! This is most likely a problem with the hull-ship-base package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run clean && npm run build:server
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs hull-ship-base
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!
       npm ERR!     npm owner ls hull-ship-base
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/node_modules/hull-ship-base/npm-debug.log
       npm ERR! Linux 3.13.0-105-generic
       npm ERR! argv "/tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/.heroku/node/bin/node" "/tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/.npmrc"
       npm ERR! node v5.12.0
       npm ERR! npm  v2.15.11
       npm ERR! code ELIFECYCLE
       
       npm ERR! hull-ship-base@0.1.0 postinstall: `npm run build`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the hull-ship-base@0.1.0 postinstall script 'npm run build'.
       npm ERR! This is most likely a problem with the hull-ship-base package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run build
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs hull-ship-base
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!
       npm ERR!     npm owner ls hull-ship-base
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_323b1ff82582a76dd3e42fcf6b749c7e/hull-ships-hull-webhooks-8ce0102/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by michaloo** [comment] 2017-02-18 15:18
Apparently the problem was caused by older version of nodejs. I've just pushed a fix which solved the problem on our end, please give it a try too.

**Closed** 2017-03-09 17:31 UTC
